# This file is an override; do not run alone.
# Use together with docker-compose.yml:
#   docker compose -f docker-compose.yml -f docker-compose.local.yml up --build
version: "3.8"

x-affine-image: &affine_image
  image: affine:local

services:
  validator:
    <<: *affine_image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env:ro
      - validator-cache:/app/data/blocks
      - /var/run/docker.sock:/var/run/docker.sock
  runner:
    <<: *affine_image
    volumes:
      - ./.env:/app/.env:ro
      - /var/run/docker.sock:/var/run/docker.sock
  signer:
    <<: *affine_image 