#!/usr/bin/env python3
"""Seed the Track M eval archive from cached king_0 (= stock 35B-A3B) rollouts.

King Zero's rollouts were generated by Track A from the SAME base model, and
the teacher rollouts by the SAME 27B teacher, so the (king0, teacher) pairs
are valid seed data. Emits:
  archive.jsonl     seed rows (dver=seed, score=None)
  seed_pairs.jsonl  judge-v0 training pairs {prefix_text, ref, mine}
  held_pairs.jsonl  200 held-out gate pairs (never trained on)
"""
from __future__ import annotations

import argparse
import json
import random
import sys
import time

sys.path.insert(0, "/root/work")
from gad_common import both_text, load_rollout_cache, load_turns  # noqa: E402
from trackM_common import render_prefix, valid_action  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--turns", default="/root/work/turns.jsonl.gz")
    ap.add_argument("--teacher-train", default="/dshare/gad/teacher_train.jsonl")
    ap.add_argument("--teacher-heldout", default="/dshare/gad/teacher_heldout.jsonl")
    ap.add_argument("--king0", default="/root/work/gen_base_rollouts_trackA.jsonl")
    ap.add_argument("--n-seed", type=int, default=1600)
    ap.add_argument("--max-chars", type=int, default=21504)  # 3584 tokens * 6
    ap.add_argument("--work", default="/dshare/koth")
    args = ap.parse_args()

    turns = load_turns(args.turns)
    t_train = load_rollout_cache(args.teacher_train)
    t_held = load_rollout_cache(args.teacher_heldout)

    king0 = {}
    for line in open(args.king0):
        r = json.loads(line)
        for c in r.get("candidates") or []:
            if c.get("z") and valid_action(c.get("y") or ""):
                king0[r["turn_id"]] = c
                break

    held_ids = set(t_held)
    pool = sorted(t for t in t_train
                  if t in turns and t in king0 and t not in held_ids)
    rng = random.Random(120)
    seed_ids = sorted(rng.sample(pool, min(args.n_seed, len(pool))))
    print(f"king0 usable={len(king0)} pool={len(pool)} seed={len(seed_ids)}")

    ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    with open(f"{args.work}/archive.jsonl", "a") as arc, \
         open(f"{args.work}/seed_pairs.jsonl", "w") as sp:
        for tid in seed_ids:
            k = king0[tid]
            ref = both_text(t_train[tid][0]["z"], t_train[tid][0]["y"])
            mine = both_text(k["z"], k["y"])
            prefix = render_prefix(turns[tid], args.max_chars)
            arc.write(json.dumps({
                "ts": ts, "turn_id": tid, "model": "king", "ckpt": "king0_base",
                "dver": "seed", "z": k["z"], "y": k["y"], "ref": ref,
                "score": None, "valid": True}) + "\n")
            sp.write(json.dumps({"turn_id": tid, "prefix_text": prefix,
                                 "ref": ref, "mine": mine}) + "\n")

    n_held = 0
    with open(f"{args.work}/held_pairs.jsonl", "w") as hp:
        for tid in sorted(held_ids):
            if tid not in turns or tid not in king0:
                continue
            k = king0[tid]
            ref = both_text(t_held[tid][0]["z"], t_held[tid][0]["y"])
            hp.write(json.dumps({
                "turn_id": tid,
                "prefix_text": render_prefix(turns[tid], args.max_chars),
                "ref": ref, "mine": both_text(k["z"], k["y"])}) + "\n")
            n_held += 1
    print(f"seed_pairs={len(seed_ids)} held_pairs={n_held}")
    print("SEED_DONE")


if __name__ == "__main__":
    main()
