"""affine-rcore-v1: reasoning-core - formally verified planning / logic / regex / math tasks.

v1 port of the Hub's `sileod/reasoning-core-env` (v0, 15 stars): rows of
`reasoning-core/symbolic-reasoning-env` (train; the v0 env's `formal-reasoning-env` id redirects to it) generated by the `reasoning_core`
library, each with a `prompt`, a serialized `answer` and `metadata` naming the
generator (`_task`); `reasoning_core.score_answer(answer, info)` verifies the
reply's `<answer>...</answer>` content formally (0 / 1). The survey's 6-task
teacher probe: 5/6, replies 0.1-1.8k tokens (in band, fits the ref cap).

Shape: single turn under the `null` harness, `text` dialect. A real *system*
message is added (upstream used reasoning-gym's DeepSeekZero prompt in the
system slot: think, then answer inside `<answer>` tags - kept in spirit).

Task identity: `name = "rcore-" + sha256(prompt)[:12]` (rollouts/catalog.py
`_rcore_meta`); rows whose generator is unknown to the installed
`reasoning_core` are skipped, as upstream does.
"""

from __future__ import annotations

import hashlib
import json

import verifiers.v1 as vf
from datasets import load_dataset
from reasoning_core import list_tasks, score_answer

DATASET = "reasoning-core/symbolic-reasoning-env"   # the Hub env's `formal-reasoning-env` id redirects here
SPLIT = "train"
SYSTEM = (
    "You solve formal reasoning tasks (planning, logic, regular expressions, "
    "mathematics). Think step by step, then give the final answer once, "
    "inside <answer> and </answer> tags, in exactly the format the task asks "
    "for. Your visible reply is graded as a whole."
)


def task_name(prompt: str) -> str:
    return "rcore-" + hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:12]


def metadata_of(row: dict) -> dict:
    meta = row.get("metadata") or {}
    if isinstance(meta, str):
        try:
            meta = json.loads(meta)
        except json.JSONDecodeError:
            meta = {}
    return meta or {}


def generator_of(row: dict) -> str:
    meta = metadata_of(row)
    return str(meta.get("_task") or row.get("task") or meta.get("task") or "")


def extract_answer(text: str, tag: str = "answer") -> str:
    if text.strip().startswith("<prompt>"):
        text = text.split("</prompt>")[-1]
    return text.split(f"<{tag}>")[-1].split(f"</{tag}>")[0]


class _Info(dict):
    """reasoning_core.score_answer reads `info.answer` / `info.metadata` (an EasyDict upstream)."""

    def __getattr__(self, name):
        try:
            return self[name]
        except KeyError as exc:
            raise AttributeError(name) from exc


class RCoreData(vf.TaskData):
    answer: str
    metadata_json: str
    generator: str


class RCoreTask(vf.Task[RCoreData]):
    @vf.reward(weight=1.0)
    async def correct(self, trace: vf.Trace) -> float:
        reply = extract_answer(trace.last_reply or "")
        info = _Info(answer=self.data.answer, metadata=_Info(json.loads(self.data.metadata_json)))
        try:
            return float(score_answer(reply, info))
        except Exception as exc:  # noqa: BLE001 - a scorer error on a malformed reply is a miss
            trace.info["score_error"] = str(exc)[:300]
            return 0.0


class RCoreConfig(vf.TasksetConfig):
    tasks: list[str] = []
    """Task names to load (empty = the whole train split of supported generators)."""
    max_rows: int = 20000
    """Rows scanned from the streaming train split (the pool is large; the
    catalog scans the same prefix)."""
    task_system_prompt: str = SYSTEM


class RCoreTaskset(vf.Taskset[RCoreTask, RCoreConfig]):
    def load(self) -> list[RCoreTask]:
        cfg = self.config
        want = set(cfg.tasks)
        available = set(list_tasks())
        rows = load_dataset(DATASET, split=SPLIT, streaming=True)
        tasks: list[RCoreTask] = []
        for i, row in enumerate(rows):
            if i >= cfg.max_rows:
                break
            gen = generator_of(row)
            if gen not in available:
                continue
            prompt = str(row["prompt"])
            name = task_name(prompt)
            if want and name not in want:
                continue
            tasks.append(RCoreTask(
                RCoreData(idx=i, name=name, system_prompt=cfg.task_system_prompt, prompt=prompt,
                          answer=str(row["answer"]), metadata_json=json.dumps(metadata_of(row)),
                          generator=gen),
                cfg.task,
            ))
        return tasks
