name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * *'  # 3:15 AM ET (7:15 UTC)

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --dev

    - name: Run unit tests
      run: uv run test --unit