name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * *'  # 3:15 AM ET (7:15 UTC)

jobs:
  docker-sanity-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Verify Docker and Docker Compose
      run: |
        docker --version
        docker compose version

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --dev

    - name: Copy example.env to .env for testing
      run: cp .env.example .env

    - name: Run tests
      run: uv run test --unit
