# This is a config for E2B sandbox template.
# You can use template ID (1exjm9ymmgo60v4zhkco) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("1exjm9ymmgo60v4zhkco") # Sync sandbox
# sandbox = await AsyncSandbox.create("1exjm9ymmgo60v4zhkco") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('1exjm9ymmgo60v4zhkco')

team_id = "ff0c49d6-e173-4e62-af6d-a55f40539bfc"
dockerfile = "e2b.Dockerfile"
template_id = "1exjm9ymmgo60v4zhkco"
